name: Build Flutter APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Install Flutter Manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1 _flutter
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Doctor & Dependencies
        run: |
          flutter doctor
          flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
